export const data =[
    {
        "id": 6339,
        "projects": 123,
        "cost_codes": 28,
        "project_floor_phases": 998,
        "name": "Lay out",
        "unit": "EA",
        "code_labor": "11120.001.1",
        "code_material": "11120.002.1",
        "production": 100,
        "man_days_allotted": 10,
        "date": "2024-03-05",
        "priority": 1,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "General Condition",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6340,
        "projects": 123,
        "cost_codes": 29,
        "project_floor_phases": 998,
        "name": "Supervision",
        "unit": "EA",
        "code_labor": "11100.001.1",
        "code_material": "11100.002.1",
        "production": 1,
        "man_days_allotted": 30,
        "date": "2024-03-09",
        "priority": 2,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 30,
        "wage_cost": 37.74,
        "floor_name": "General Condition",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6341,
        "projects": 123,
        "cost_codes": 30,
        "project_floor_phases": 998,
        "name": "Clean Up & Stocking",
        "unit": "MD",
        "code_labor": "11130.001.1",
        "code_material": "11130.002.1",
        "production": 12,
        "man_days_allotted": 12,
        "date": "2024-02-18",
        "priority": 1,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 15.84,
        "floor_name": "General Condition",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6871,
        "projects": 123,
        "cost_codes": 629,
        "project_floor_phases": 998,
        "name": "Ticket Work #01",
        "unit": "EA",
        "code_labor": "21000.001.2",
        "code_material": "21000.002.2",
        "production": 1,
        "man_days_allotted": 3,
        "date": "2024-02-18",
        "priority": 0,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "General Condition",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6343,
        "projects": 123,
        "cost_codes": 9,
        "project_floor_phases": 999,
        "name": "Frame Interior Walls",
        "unit": "LF",
        "code_labor": "91100.001.2",
        "code_material": "91100.002.2",
        "production": 50,
        "man_days_allotted": 1.5,
        "date": "2024-02-28",
        "priority": 2,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6344,
        "projects": 123,
        "cost_codes": 613,
        "project_floor_phases": 999,
        "name": "Temporary Walls",
        "unit": "EA",
        "code_labor": "61300.001.6",
        "code_material": "61300.002.6",
        "production": 15,
        "man_days_allotted": 0.5,
        "date": "2024-02-18",
        "priority": 18,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6345,
        "projects": 123,
        "cost_codes": 22,
        "project_floor_phases": 999,
        "name": "Frame Interior Soffits",
        "unit": "LF",
        "code_labor": "91110.001.3",
        "code_material": "91110.002.3",
        "production": 40,
        "man_days_allotted": 1,
        "date": "2024-03-08",
        "priority": 14,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6347,
        "projects": 123,
        "cost_codes": 21,
        "project_floor_phases": 999,
        "name": "Install Insulation",
        "unit": "SF",
        "code_labor": "71110.001.1",
        "code_material": "71110.002.1",
        "production": 1300,
        "man_days_allotted": 1,
        "date": "2024-03-07",
        "priority": 13,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6348,
        "projects": 123,
        "cost_codes": 15,
        "project_floor_phases": 999,
        "name": "Hang Bottoms",
        "unit": "SF",
        "code_labor": "91201.011.1",
        "code_material": "91201.012.1",
        "production": 800,
        "man_days_allotted": 2,
        "date": "2024-02-18",
        "priority": 12,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6349,
        "projects": 123,
        "cost_codes": 17,
        "project_floor_phases": 999,
        "name": "Hang Tops",
        "unit": "SF",
        "code_labor": "91202.001.1",
        "code_material": "91202.002.1",
        "production": 350,
        "man_days_allotted": 0.8,
        "date": "2024-02-18",
        "priority": 11,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6350,
        "projects": 123,
        "cost_codes": 25,
        "project_floor_phases": 999,
        "name": "Hang Drywall Ceiling",
        "unit": "SF",
        "code_labor": "91202.001.2",
        "code_material": "91202.002.2",
        "production": 300,
        "man_days_allotted": 0.5,
        "date": "2024-02-18",
        "priority": 10,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6351,
        "projects": 123,
        "cost_codes": 20,
        "project_floor_phases": 999,
        "name": "Caulking",
        "unit": "LF",
        "code_labor": "71720.001.1",
        "code_material": "71720.002.1",
        "production": 400,
        "man_days_allotted": 1,
        "date": "2024-03-07",
        "priority": 9,
        "is_active": true,
        "assigned_employees": 'Tejas',
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 29.94,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6352,
        "projects": 123,
        "cost_codes": 923,
        "project_floor_phases": 999,
        "name": "Finishing",
        "unit": "SF",
        "code_labor": "91500.001._",
        "code_material": "91500.001._",
        "production": 800,
        "man_days_allotted": 10,
        "date": "2024-03-07",
        "priority": 8,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 34.04,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6353,
        "projects": 123,
        "cost_codes": 27,
        "project_floor_phases": 999,
        "name": "In Wall Blocking",
        "unit": "LF",
        "code_labor": "91120.001.2",
        "code_material": "91120.002.2",
        "production": 200,
        "man_days_allotted": 4,
        "date": "2024-03-07",
        "priority": 7,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6354,
        "projects": 123,
        "cost_codes": 50,
        "project_floor_phases": 999,
        "name": "Install HM Door Frames",
        "unit": "EA",
        "code_labor": "81110.001.",
        "code_material": "81110.002._",
        "production": 1,
        "man_days_allotted": 4,
        "date": "2024-02-18",
        "priority": 17,
        "is_active": true,
        "assigned_employees": 'Tejas',
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6355,
        "projects": 123,
        "cost_codes": 23,
        "project_floor_phases": 999,
        "name": "Frame Drywall Ceilings",
        "unit": "SF",
        "code_labor": "91111.001.1",
        "code_material": "91111.002.1",
        "production": 250,
        "man_days_allotted": 3.2,
        "date": "2024-03-07",
        "priority": 6,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6357,
        "projects": 123,
        "cost_codes": 876,
        "project_floor_phases": 999,
        "name": "Acoustical Ceilings Grid",
        "unit": "SF",
        "code_labor": "91700.001._",
        "code_material": "91700.001._",
        "production": 400,
        "man_days_allotted": 3,
        "date": "2024-02-18",
        "priority": 5,
        "is_active": true,
        "assigned_employees": null,
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 50,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    },
    {
        "id": 6358,
        "projects": 123,
        "cost_codes": 32,
        "project_floor_phases": 999,
        "name": "Install ACT Tiles",
        "unit": "SF",
        "code_labor": "91720.001.1",
        "code_material": "91720.002.1",
        "production": 900,
        "man_days_allotted": 2,
        "date": null,
        "priority": 4,
        "is_active": true,
        "assigned_employees": 'XYZ',
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37.74,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": [
            {
                "id": 112,
                "software_alias_id": 6,
                "cost_codes_id": 32,
                "value": "121",
                "software_alias_name": "Edge"
            }
        ]
    },
    {
        "id": 6401,
        "projects": 123,
        "cost_codes": 1054,
        "project_floor_phases": 999,
        "name": "Demolition",
        "unit": "MD",
        "code_labor": "91600.001.1",
        "code_material": "91600.002.1",
        "production": 1,
        "man_days_allotted": 17,
        "date": "2024-02-18",
        "priority": 16,
        "is_active": true,
        "assigned_employees": 'ABC',
        "awarded_contractors": [],
        "regular_cost": 25,
        "wage_cost": 37,
        "floor_name": "Basement",
        "notes_count": 0,
        "software_aliases": []
    }
]